#! /bin/bash
set -x
cd "$HOME"
for f in .bash_profile .bash_login .bash_logout; do
  if [ -e "$f" ]; then
    echo "FATAL: $f exists, please (re)move."
    exit -1
  fi
done
ln -s rwgk_config/profile .profile
ln -s rwgk_config/bashrc .bashrc
ln -s rwgk_config/inputrc .inputrc
ln -s rwgk_config/vimrc .vimrc
mkdir -p "$HOME/.vim/backup"
mkdir -p "$HOME/.vim/swap"
mkdir -p "$HOME/.vim/undo"
