#!/bin/sh

get_filtered_status() {
    git status --short --no-column | grep -v -E '^\?\? .*Venv/'
}

if [ "$(get_filtered_status | wc -l)" -gt 0 ]; then
    echo ".git/hooks/pre-push: ERROR: dirty state:"
    get_filtered_status
    exit 1
fi
